name: IAS Scan test
on:
  push:
    branches: [ master ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - id: my-scan
        uses: sstephenson-r7/insightappsec-scan-github-actions@v1.3.0
        with:
          region: us
          api-key: ${{ secrets.IAS_API_KEY }}
          scan-config-id: '77a063fa-7aaa-489d-8f44-8ae2ce4bc387'
          vuln-query: null
      - name: Upload findings
        if: always()
        run: echo "${{ steps.my-scan.outputs.scan-findings }}"
  deploy:
    runs-on: ubuntu-latest
    needs: [scan]
    steps:
      - name: Deploy artifact
        run: echo "Deploying..."
